[2023-11-05T12:57:55.398+0400] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: experiment.experiment manual__2023-11-05T08:57:49.078840+00:00 [queued]>
[2023-11-05T12:57:55.400+0400] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: experiment.experiment manual__2023-11-05T08:57:49.078840+00:00 [queued]>
[2023-11-05T12:57:55.400+0400] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-05T12:57:55.407+0400] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): experiment> on 2023-11-05 08:57:49.078840+00:00
[2023-11-05T12:57:55.410+0400] {standard_task_runner.py:57} INFO - Started process 52097 to run task
[2023-11-05T12:57:55.412+0400] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'experiment', 'experiment', 'manual__2023-11-05T08:57:49.078840+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/experiment.py', '--cfg-path', '/tmp/tmpk42judvd']
[2023-11-05T12:57:55.412+0400] {standard_task_runner.py:85} INFO - Job 11: Subtask experiment
[2023-11-05T12:57:55.428+0400] {task_command.py:416} INFO - Running <TaskInstance: experiment.experiment manual__2023-11-05T08:57:49.078840+00:00 [running]> on host primary
[2023-11-05T12:57:55.452+0400] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='experiment' AIRFLOW_CTX_TASK_ID='experiment' AIRFLOW_CTX_EXECUTION_DATE='2023-11-05T08:57:49.078840+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-05T08:57:49.078840+00:00'
[2023-11-05T12:57:55.459+0400] {experiment.py:34} INFO - LinearRegression() is about to start training
[2023-11-05T12:57:55.461+0400] {experiment.py:36} INFO - LinearRegression() training is finished
[2023-11-05T12:57:55.462+0400] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-11-05T12:57:55.464+0400] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-11-05T12:57:55.465+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-11-05T12:57:55.465+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-11-05T12:57:55.465+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-11-05T12:57:55.465+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-11-05T12:57:55.465+0400] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-11-05T12:57:55.465+0400] {logging_mixin.py:151} WARNING - Call stack:
[2023-11-05T12:57:55.466+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/bin/airflow", line 8, in <module>
    sys.exit(main())
[2023-11-05T12:57:55.466+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/__main__.py", line 59, in main
    args.func(args)
[2023-11-05T12:57:55.466+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-11-05T12:57:55.466+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-11-05T12:57:55.466+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 431, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-11-05T12:57:55.466+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 209, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-11-05T12:57:55.466+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 271, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-11-05T12:57:55.466+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-11-05T12:57:55.466+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-11-05T12:57:55.466+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-11-05T12:57:55.466+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-11-05T12:57:55.466+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-11-05T12:57:55.466+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-11-05T12:57:55.466+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-11-05T12:57:55.466+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-11-05T12:57:55.466+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 431, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-11-05T12:57:55.466+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 211, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-11-05T12:57:55.466+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 290, in _run_raw_task
    return ti._run_raw_task(
[2023-11-05T12:57:55.466+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-11-05T12:57:55.466+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-11-05T12:57:55.466+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-11-05T12:57:55.466+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-11-05T12:57:55.466+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-11-05T12:57:55.466+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-11-05T12:57:55.466+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-11-05T12:57:55.466+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/scripts/experiment.py", line 39, in run
    logger.info(f'{model} mse: ', mse)
[2023-11-05T12:57:55.466+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1477, in info
    self._log(INFO, msg, args, **kwargs)
[2023-11-05T12:57:55.467+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
[2023-11-05T12:57:55.467+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
[2023-11-05T12:57:55.467+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
[2023-11-05T12:57:55.467+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
[2023-11-05T12:57:55.467+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/log/file_task_handler.py", line 210, in emit
    self.handler.emit(record)
[2023-11-05T12:57:55.467+0400] {logging_mixin.py:151} WARNING - Message: 'LinearRegression() mse: '
Arguments: (20622.3320420073,)
[2023-11-05T12:57:55.467+0400] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-11-05T12:57:55.467+0400] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-11-05T12:57:55.467+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-11-05T12:57:55.467+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-11-05T12:57:55.467+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-11-05T12:57:55.467+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-11-05T12:57:55.467+0400] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-11-05T12:57:55.467+0400] {logging_mixin.py:151} WARNING - Call stack:
[2023-11-05T12:57:55.467+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/bin/airflow", line 8, in <module>
    sys.exit(main())
[2023-11-05T12:57:55.467+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/__main__.py", line 59, in main
    args.func(args)
[2023-11-05T12:57:55.467+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-11-05T12:57:55.467+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-11-05T12:57:55.467+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 431, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-11-05T12:57:55.467+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 209, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-11-05T12:57:55.468+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 271, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-11-05T12:57:55.468+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-11-05T12:57:55.468+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-11-05T12:57:55.468+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-11-05T12:57:55.468+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-11-05T12:57:55.468+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-11-05T12:57:55.468+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-11-05T12:57:55.468+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-11-05T12:57:55.468+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-11-05T12:57:55.468+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 431, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-11-05T12:57:55.468+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 211, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-11-05T12:57:55.468+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 290, in _run_raw_task
    return ti._run_raw_task(
[2023-11-05T12:57:55.468+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-11-05T12:57:55.468+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-11-05T12:57:55.468+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-11-05T12:57:55.468+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-11-05T12:57:55.468+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-11-05T12:57:55.468+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-11-05T12:57:55.468+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-11-05T12:57:55.468+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/scripts/experiment.py", line 41, in run
    logger.info(f'{model} mae: ', mae)
[2023-11-05T12:57:55.468+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1477, in info
    self._log(INFO, msg, args, **kwargs)
[2023-11-05T12:57:55.468+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
[2023-11-05T12:57:55.468+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
[2023-11-05T12:57:55.468+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
[2023-11-05T12:57:55.468+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
[2023-11-05T12:57:55.468+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/log/file_task_handler.py", line 210, in emit
    self.handler.emit(record)
[2023-11-05T12:57:55.468+0400] {logging_mixin.py:151} WARNING - Message: 'LinearRegression() mae: '
Arguments: (96.22724276111093,)
[2023-11-05T12:57:55.468+0400] {experiment.py:34} INFO - Lasso(alpha=0.5) is about to start training
[2023-11-05T12:57:55.470+0400] {experiment.py:36} INFO - Lasso(alpha=0.5) training is finished
[2023-11-05T12:57:55.470+0400] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-11-05T12:57:55.471+0400] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-11-05T12:57:55.471+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-11-05T12:57:55.471+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-11-05T12:57:55.471+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-11-05T12:57:55.471+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-11-05T12:57:55.471+0400] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-11-05T12:57:55.471+0400] {logging_mixin.py:151} WARNING - Call stack:
[2023-11-05T12:57:55.471+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/bin/airflow", line 8, in <module>
    sys.exit(main())
[2023-11-05T12:57:55.471+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/__main__.py", line 59, in main
    args.func(args)
[2023-11-05T12:57:55.471+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-11-05T12:57:55.471+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-11-05T12:57:55.471+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 431, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-11-05T12:57:55.471+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 209, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-11-05T12:57:55.471+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 271, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-11-05T12:57:55.471+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-11-05T12:57:55.471+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-11-05T12:57:55.471+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-11-05T12:57:55.471+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-11-05T12:57:55.471+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-11-05T12:57:55.471+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-11-05T12:57:55.471+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-11-05T12:57:55.471+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-11-05T12:57:55.471+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 431, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-11-05T12:57:55.471+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 211, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-11-05T12:57:55.471+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 290, in _run_raw_task
    return ti._run_raw_task(
[2023-11-05T12:57:55.471+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-11-05T12:57:55.471+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-11-05T12:57:55.471+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-11-05T12:57:55.471+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-11-05T12:57:55.472+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-11-05T12:57:55.472+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-11-05T12:57:55.472+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-11-05T12:57:55.472+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/scripts/experiment.py", line 39, in run
    logger.info(f'{model} mse: ', mse)
[2023-11-05T12:57:55.472+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1477, in info
    self._log(INFO, msg, args, **kwargs)
[2023-11-05T12:57:55.472+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
[2023-11-05T12:57:55.472+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
[2023-11-05T12:57:55.472+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
[2023-11-05T12:57:55.472+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
[2023-11-05T12:57:55.472+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/log/file_task_handler.py", line 210, in emit
    self.handler.emit(record)
[2023-11-05T12:57:55.472+0400] {logging_mixin.py:151} WARNING - Message: 'Lasso(alpha=0.5) mse: '
Arguments: (16573.98470528784,)
[2023-11-05T12:57:55.472+0400] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-11-05T12:57:55.472+0400] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-11-05T12:57:55.472+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-11-05T12:57:55.472+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-11-05T12:57:55.472+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-11-05T12:57:55.472+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-11-05T12:57:55.472+0400] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-11-05T12:57:55.472+0400] {logging_mixin.py:151} WARNING - Call stack:
[2023-11-05T12:57:55.472+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/bin/airflow", line 8, in <module>
    sys.exit(main())
[2023-11-05T12:57:55.472+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/__main__.py", line 59, in main
    args.func(args)
[2023-11-05T12:57:55.472+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-11-05T12:57:55.472+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-11-05T12:57:55.473+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 431, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-11-05T12:57:55.473+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 209, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-11-05T12:57:55.473+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 271, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-11-05T12:57:55.473+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-11-05T12:57:55.473+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-11-05T12:57:55.473+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-11-05T12:57:55.473+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-11-05T12:57:55.473+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-11-05T12:57:55.473+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-11-05T12:57:55.473+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-11-05T12:57:55.473+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-11-05T12:57:55.473+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 431, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-11-05T12:57:55.473+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 211, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-11-05T12:57:55.473+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 290, in _run_raw_task
    return ti._run_raw_task(
[2023-11-05T12:57:55.473+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-11-05T12:57:55.473+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-11-05T12:57:55.473+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-11-05T12:57:55.473+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-11-05T12:57:55.473+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-11-05T12:57:55.473+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-11-05T12:57:55.473+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-11-05T12:57:55.473+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/scripts/experiment.py", line 41, in run
    logger.info(f'{model} mae: ', mae)
[2023-11-05T12:57:55.473+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1477, in info
    self._log(INFO, msg, args, **kwargs)
[2023-11-05T12:57:55.473+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
[2023-11-05T12:57:55.473+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
[2023-11-05T12:57:55.473+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
[2023-11-05T12:57:55.473+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
[2023-11-05T12:57:55.473+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/log/file_task_handler.py", line 210, in emit
    self.handler.emit(record)
[2023-11-05T12:57:55.473+0400] {logging_mixin.py:151} WARNING - Message: 'Lasso(alpha=0.5) mae: '
Arguments: (90.98391334330802,)
[2023-11-05T12:57:55.473+0400] {experiment.py:34} INFO - Ridge(alpha=0.5) is about to start training
[2023-11-05T12:57:55.474+0400] {experiment.py:36} INFO - Ridge(alpha=0.5) training is finished
[2023-11-05T12:57:55.475+0400] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-11-05T12:57:55.475+0400] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-11-05T12:57:55.475+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-11-05T12:57:55.475+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-11-05T12:57:55.475+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-11-05T12:57:55.475+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-11-05T12:57:55.475+0400] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-11-05T12:57:55.475+0400] {logging_mixin.py:151} WARNING - Call stack:
[2023-11-05T12:57:55.475+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/bin/airflow", line 8, in <module>
    sys.exit(main())
[2023-11-05T12:57:55.475+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/__main__.py", line 59, in main
    args.func(args)
[2023-11-05T12:57:55.475+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-11-05T12:57:55.476+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-11-05T12:57:55.476+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 431, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-11-05T12:57:55.476+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 209, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-11-05T12:57:55.476+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 271, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-11-05T12:57:55.476+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-11-05T12:57:55.476+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-11-05T12:57:55.476+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-11-05T12:57:55.476+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-11-05T12:57:55.476+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-11-05T12:57:55.476+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-11-05T12:57:55.476+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-11-05T12:57:55.476+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-11-05T12:57:55.476+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 431, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-11-05T12:57:55.476+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 211, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-11-05T12:57:55.476+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 290, in _run_raw_task
    return ti._run_raw_task(
[2023-11-05T12:57:55.476+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-11-05T12:57:55.476+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-11-05T12:57:55.476+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-11-05T12:57:55.476+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-11-05T12:57:55.476+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-11-05T12:57:55.476+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-11-05T12:57:55.476+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-11-05T12:57:55.476+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/scripts/experiment.py", line 39, in run
    logger.info(f'{model} mse: ', mse)
[2023-11-05T12:57:55.476+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1477, in info
    self._log(INFO, msg, args, **kwargs)
[2023-11-05T12:57:55.476+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
[2023-11-05T12:57:55.476+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
[2023-11-05T12:57:55.476+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
[2023-11-05T12:57:55.476+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
[2023-11-05T12:57:55.476+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/log/file_task_handler.py", line 210, in emit
    self.handler.emit(record)
[2023-11-05T12:57:55.476+0400] {logging_mixin.py:151} WARNING - Message: 'Ridge(alpha=0.5) mse: '
Arguments: (14964.769258848102,)
[2023-11-05T12:57:55.477+0400] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-11-05T12:57:55.477+0400] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-11-05T12:57:55.477+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-11-05T12:57:55.477+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-11-05T12:57:55.477+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-11-05T12:57:55.477+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-11-05T12:57:55.477+0400] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-11-05T12:57:55.477+0400] {logging_mixin.py:151} WARNING - Call stack:
[2023-11-05T12:57:55.477+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/bin/airflow", line 8, in <module>
    sys.exit(main())
[2023-11-05T12:57:55.477+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/__main__.py", line 59, in main
    args.func(args)
[2023-11-05T12:57:55.477+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-11-05T12:57:55.477+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-11-05T12:57:55.477+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 431, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-11-05T12:57:55.477+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 209, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-11-05T12:57:55.477+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 271, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-11-05T12:57:55.477+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-11-05T12:57:55.477+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-11-05T12:57:55.477+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-11-05T12:57:55.477+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-11-05T12:57:55.477+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-11-05T12:57:55.477+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-11-05T12:57:55.477+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-11-05T12:57:55.477+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-11-05T12:57:55.477+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 431, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-11-05T12:57:55.477+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 211, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-11-05T12:57:55.477+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 290, in _run_raw_task
    return ti._run_raw_task(
[2023-11-05T12:57:55.477+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-11-05T12:57:55.477+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-11-05T12:57:55.477+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-11-05T12:57:55.477+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-11-05T12:57:55.477+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-11-05T12:57:55.477+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-11-05T12:57:55.477+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-11-05T12:57:55.477+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/scripts/experiment.py", line 41, in run
    logger.info(f'{model} mae: ', mae)
[2023-11-05T12:57:55.478+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1477, in info
    self._log(INFO, msg, args, **kwargs)
[2023-11-05T12:57:55.478+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
[2023-11-05T12:57:55.478+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
[2023-11-05T12:57:55.478+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
[2023-11-05T12:57:55.478+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
[2023-11-05T12:57:55.478+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/log/file_task_handler.py", line 210, in emit
    self.handler.emit(record)
[2023-11-05T12:57:55.478+0400] {logging_mixin.py:151} WARNING - Message: 'Ridge(alpha=0.5) mae: '
Arguments: (89.18991972918292,)
[2023-11-05T12:57:55.478+0400] {experiment.py:34} INFO - KNeighborsRegressor(n_neighbors=3, weights='distance') is about to start training
[2023-11-05T12:57:55.478+0400] {experiment.py:36} INFO - KNeighborsRegressor(n_neighbors=3, weights='distance') training is finished
[2023-11-05T12:57:55.490+0400] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-11-05T12:57:55.490+0400] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-11-05T12:57:55.490+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-11-05T12:57:55.490+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-11-05T12:57:55.490+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-11-05T12:57:55.490+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-11-05T12:57:55.490+0400] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-11-05T12:57:55.490+0400] {logging_mixin.py:151} WARNING - Call stack:
[2023-11-05T12:57:55.490+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/bin/airflow", line 8, in <module>
    sys.exit(main())
[2023-11-05T12:57:55.491+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/__main__.py", line 59, in main
    args.func(args)
[2023-11-05T12:57:55.491+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-11-05T12:57:55.491+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-11-05T12:57:55.491+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 431, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-11-05T12:57:55.491+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 209, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-11-05T12:57:55.491+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 271, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-11-05T12:57:55.491+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-11-05T12:57:55.491+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-11-05T12:57:55.491+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-11-05T12:57:55.491+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-11-05T12:57:55.491+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-11-05T12:57:55.491+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-11-05T12:57:55.491+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-11-05T12:57:55.491+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-11-05T12:57:55.491+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 431, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-11-05T12:57:55.491+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 211, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-11-05T12:57:55.491+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 290, in _run_raw_task
    return ti._run_raw_task(
[2023-11-05T12:57:55.491+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-11-05T12:57:55.491+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-11-05T12:57:55.491+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-11-05T12:57:55.491+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-11-05T12:57:55.491+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-11-05T12:57:55.491+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-11-05T12:57:55.491+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-11-05T12:57:55.491+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/scripts/experiment.py", line 39, in run
    logger.info(f'{model} mse: ', mse)
[2023-11-05T12:57:55.491+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1477, in info
    self._log(INFO, msg, args, **kwargs)
[2023-11-05T12:57:55.491+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
[2023-11-05T12:57:55.491+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
[2023-11-05T12:57:55.491+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
[2023-11-05T12:57:55.491+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
[2023-11-05T12:57:55.491+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/log/file_task_handler.py", line 210, in emit
    self.handler.emit(record)
[2023-11-05T12:57:55.491+0400] {logging_mixin.py:151} WARNING - Message: "KNeighborsRegressor(n_neighbors=3, weights='distance') mse: "
Arguments: (14255.610884554422,)
[2023-11-05T12:57:55.492+0400] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-11-05T12:57:55.492+0400] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-11-05T12:57:55.492+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-11-05T12:57:55.492+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-11-05T12:57:55.492+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-11-05T12:57:55.492+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-11-05T12:57:55.492+0400] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-11-05T12:57:55.492+0400] {logging_mixin.py:151} WARNING - Call stack:
[2023-11-05T12:57:55.492+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/bin/airflow", line 8, in <module>
    sys.exit(main())
[2023-11-05T12:57:55.492+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/__main__.py", line 59, in main
    args.func(args)
[2023-11-05T12:57:55.492+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-11-05T12:57:55.492+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-11-05T12:57:55.492+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 431, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-11-05T12:57:55.492+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 209, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-11-05T12:57:55.492+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 271, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-11-05T12:57:55.492+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-11-05T12:57:55.492+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-11-05T12:57:55.492+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-11-05T12:57:55.492+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-11-05T12:57:55.492+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-11-05T12:57:55.492+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-11-05T12:57:55.492+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-11-05T12:57:55.492+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-11-05T12:57:55.492+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 431, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-11-05T12:57:55.492+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 211, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-11-05T12:57:55.492+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 290, in _run_raw_task
    return ti._run_raw_task(
[2023-11-05T12:57:55.492+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-11-05T12:57:55.492+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-11-05T12:57:55.492+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-11-05T12:57:55.492+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-11-05T12:57:55.493+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-11-05T12:57:55.493+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-11-05T12:57:55.493+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-11-05T12:57:55.493+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/scripts/experiment.py", line 41, in run
    logger.info(f'{model} mae: ', mae)
[2023-11-05T12:57:55.493+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1477, in info
    self._log(INFO, msg, args, **kwargs)
[2023-11-05T12:57:55.493+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
[2023-11-05T12:57:55.493+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
[2023-11-05T12:57:55.493+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
[2023-11-05T12:57:55.493+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
[2023-11-05T12:57:55.493+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/log/file_task_handler.py", line 210, in emit
    self.handler.emit(record)
[2023-11-05T12:57:55.493+0400] {logging_mixin.py:151} WARNING - Message: "KNeighborsRegressor(n_neighbors=3, weights='distance') mae: "
Arguments: (63.78802535989261,)
[2023-11-05T12:57:55.493+0400] {experiment.py:34} INFO - AdaBoostRegressor(n_estimators=20) is about to start training
[2023-11-05T12:57:55.507+0400] {experiment.py:36} INFO - AdaBoostRegressor(n_estimators=20) training is finished
[2023-11-05T12:57:55.509+0400] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-11-05T12:57:55.509+0400] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-11-05T12:57:55.509+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-11-05T12:57:55.509+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-11-05T12:57:55.509+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-11-05T12:57:55.509+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-11-05T12:57:55.509+0400] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-11-05T12:57:55.509+0400] {logging_mixin.py:151} WARNING - Call stack:
[2023-11-05T12:57:55.509+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/bin/airflow", line 8, in <module>
    sys.exit(main())
[2023-11-05T12:57:55.509+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/__main__.py", line 59, in main
    args.func(args)
[2023-11-05T12:57:55.509+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-11-05T12:57:55.509+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-11-05T12:57:55.509+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 431, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-11-05T12:57:55.509+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 209, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-11-05T12:57:55.509+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 271, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-11-05T12:57:55.509+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-11-05T12:57:55.509+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-11-05T12:57:55.509+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-11-05T12:57:55.509+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-11-05T12:57:55.509+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-11-05T12:57:55.509+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-11-05T12:57:55.509+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-11-05T12:57:55.509+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-11-05T12:57:55.509+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 431, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-11-05T12:57:55.509+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 211, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-11-05T12:57:55.510+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 290, in _run_raw_task
    return ti._run_raw_task(
[2023-11-05T12:57:55.510+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-11-05T12:57:55.510+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-11-05T12:57:55.510+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-11-05T12:57:55.510+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-11-05T12:57:55.510+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-11-05T12:57:55.510+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-11-05T12:57:55.510+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-11-05T12:57:55.510+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/scripts/experiment.py", line 39, in run
    logger.info(f'{model} mse: ', mse)
[2023-11-05T12:57:55.510+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1477, in info
    self._log(INFO, msg, args, **kwargs)
[2023-11-05T12:57:55.510+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
[2023-11-05T12:57:55.510+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
[2023-11-05T12:57:55.510+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
[2023-11-05T12:57:55.510+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
[2023-11-05T12:57:55.510+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/log/file_task_handler.py", line 210, in emit
    self.handler.emit(record)
[2023-11-05T12:57:55.510+0400] {logging_mixin.py:151} WARNING - Message: 'AdaBoostRegressor(n_estimators=20) mse: '
Arguments: (24599.84991060048,)
[2023-11-05T12:57:55.510+0400] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-11-05T12:57:55.510+0400] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-11-05T12:57:55.510+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-11-05T12:57:55.510+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-11-05T12:57:55.510+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-11-05T12:57:55.510+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-11-05T12:57:55.510+0400] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-11-05T12:57:55.510+0400] {logging_mixin.py:151} WARNING - Call stack:
[2023-11-05T12:57:55.511+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/bin/airflow", line 8, in <module>
    sys.exit(main())
[2023-11-05T12:57:55.511+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/__main__.py", line 59, in main
    args.func(args)
[2023-11-05T12:57:55.511+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-11-05T12:57:55.511+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-11-05T12:57:55.511+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 431, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-11-05T12:57:55.511+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 209, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-11-05T12:57:55.511+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 271, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-11-05T12:57:55.511+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-11-05T12:57:55.511+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-11-05T12:57:55.511+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-11-05T12:57:55.511+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-11-05T12:57:55.511+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-11-05T12:57:55.511+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-11-05T12:57:55.511+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-11-05T12:57:55.511+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-11-05T12:57:55.511+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 431, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-11-05T12:57:55.511+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 211, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-11-05T12:57:55.511+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 290, in _run_raw_task
    return ti._run_raw_task(
[2023-11-05T12:57:55.511+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-11-05T12:57:55.511+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-11-05T12:57:55.511+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-11-05T12:57:55.511+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-11-05T12:57:55.511+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-11-05T12:57:55.511+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-11-05T12:57:55.511+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-11-05T12:57:55.511+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/scripts/experiment.py", line 41, in run
    logger.info(f'{model} mae: ', mae)
[2023-11-05T12:57:55.511+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1477, in info
    self._log(INFO, msg, args, **kwargs)
[2023-11-05T12:57:55.511+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
[2023-11-05T12:57:55.511+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
[2023-11-05T12:57:55.511+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
[2023-11-05T12:57:55.511+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
[2023-11-05T12:57:55.511+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/log/file_task_handler.py", line 210, in emit
    self.handler.emit(record)
[2023-11-05T12:57:55.511+0400] {logging_mixin.py:151} WARNING - Message: 'AdaBoostRegressor(n_estimators=20) mae: '
Arguments: (128.51322821493494,)
[2023-11-05T12:57:55.511+0400] {experiment.py:34} INFO - GradientBoostingRegressor(n_estimators=200) is about to start training
[2023-11-05T12:57:55.581+0400] {experiment.py:36} INFO - GradientBoostingRegressor(n_estimators=200) training is finished
[2023-11-05T12:57:55.582+0400] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-11-05T12:57:55.582+0400] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-11-05T12:57:55.582+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-11-05T12:57:55.582+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-11-05T12:57:55.582+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-11-05T12:57:55.582+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-11-05T12:57:55.582+0400] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-11-05T12:57:55.582+0400] {logging_mixin.py:151} WARNING - Call stack:
[2023-11-05T12:57:55.583+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/bin/airflow", line 8, in <module>
    sys.exit(main())
[2023-11-05T12:57:55.583+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/__main__.py", line 59, in main
    args.func(args)
[2023-11-05T12:57:55.583+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-11-05T12:57:55.583+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-11-05T12:57:55.583+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 431, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-11-05T12:57:55.583+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 209, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-11-05T12:57:55.583+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 271, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-11-05T12:57:55.583+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-11-05T12:57:55.583+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-11-05T12:57:55.583+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-11-05T12:57:55.583+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-11-05T12:57:55.583+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-11-05T12:57:55.583+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-11-05T12:57:55.583+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-11-05T12:57:55.583+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-11-05T12:57:55.583+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 431, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-11-05T12:57:55.583+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 211, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-11-05T12:57:55.583+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 290, in _run_raw_task
    return ti._run_raw_task(
[2023-11-05T12:57:55.583+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-11-05T12:57:55.583+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-11-05T12:57:55.583+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-11-05T12:57:55.583+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-11-05T12:57:55.583+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-11-05T12:57:55.583+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-11-05T12:57:55.583+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-11-05T12:57:55.583+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/scripts/experiment.py", line 39, in run
    logger.info(f'{model} mse: ', mse)
[2023-11-05T12:57:55.583+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1477, in info
    self._log(INFO, msg, args, **kwargs)
[2023-11-05T12:57:55.583+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
[2023-11-05T12:57:55.583+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
[2023-11-05T12:57:55.583+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
[2023-11-05T12:57:55.583+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
[2023-11-05T12:57:55.583+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/log/file_task_handler.py", line 210, in emit
    self.handler.emit(record)
[2023-11-05T12:57:55.583+0400] {logging_mixin.py:151} WARNING - Message: 'GradientBoostingRegressor(n_estimators=200) mse: '
Arguments: (9006.572054835062,)
[2023-11-05T12:57:55.584+0400] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-11-05T12:57:55.584+0400] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-11-05T12:57:55.584+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-11-05T12:57:55.584+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-11-05T12:57:55.584+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-11-05T12:57:55.584+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-11-05T12:57:55.584+0400] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-11-05T12:57:55.584+0400] {logging_mixin.py:151} WARNING - Call stack:
[2023-11-05T12:57:55.584+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/bin/airflow", line 8, in <module>
    sys.exit(main())
[2023-11-05T12:57:55.584+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/__main__.py", line 59, in main
    args.func(args)
[2023-11-05T12:57:55.584+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-11-05T12:57:55.584+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-11-05T12:57:55.584+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 431, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-11-05T12:57:55.584+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 209, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-11-05T12:57:55.584+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 271, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-11-05T12:57:55.584+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-11-05T12:57:55.584+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-11-05T12:57:55.584+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-11-05T12:57:55.584+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-11-05T12:57:55.584+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-11-05T12:57:55.584+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-11-05T12:57:55.584+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-11-05T12:57:55.584+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-11-05T12:57:55.584+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 431, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-11-05T12:57:55.585+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 211, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-11-05T12:57:55.585+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 290, in _run_raw_task
    return ti._run_raw_task(
[2023-11-05T12:57:55.585+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-11-05T12:57:55.585+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-11-05T12:57:55.585+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-11-05T12:57:55.585+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-11-05T12:57:55.585+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-11-05T12:57:55.585+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-11-05T12:57:55.585+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-11-05T12:57:55.585+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/scripts/experiment.py", line 41, in run
    logger.info(f'{model} mae: ', mae)
[2023-11-05T12:57:55.585+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1477, in info
    self._log(INFO, msg, args, **kwargs)
[2023-11-05T12:57:55.585+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
[2023-11-05T12:57:55.585+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
[2023-11-05T12:57:55.585+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
[2023-11-05T12:57:55.585+0400] {logging_mixin.py:151} WARNING -   File "/usr/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
[2023-11-05T12:57:55.585+0400] {logging_mixin.py:151} WARNING -   File "/home/pyretttt/repos/mlops4/env/lib/python3.10/site-packages/airflow/utils/log/file_task_handler.py", line 210, in emit
    self.handler.emit(record)
[2023-11-05T12:57:55.585+0400] {logging_mixin.py:151} WARNING - Message: 'GradientBoostingRegressor(n_estimators=200) mae: '
Arguments: (57.40187073410426,)
[2023-11-05T12:57:55.585+0400] {experiment.py:47} INFO - best_estimator: GradientBoostingRegressor(n_estimators=200)
[2023-11-05T12:57:55.585+0400] {experiment.py:48} INFO - best_mse: 9006.572054835062
[2023-11-05T12:57:55.585+0400] {python.py:194} INFO - Done. Returned value was: Experiment finished successfully
[2023-11-05T12:57:55.592+0400] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=experiment, task_id=experiment, execution_date=20231105T085749, start_date=20231105T085755, end_date=20231105T085755
[2023-11-05T12:57:55.604+0400] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-05T12:57:55.609+0400] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
